### ISSUE TITLE
Build with barvinok fails

### ISSUE THREAD

**Issue by kaushikcfd** [conda-forge/islpy-feedstock#34]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

To reproduce:
```bash
$ conda install islpy barvinok
$ python -m islpy
Illegal instruction (core dumped)
```
The backtrace is:
```gdb
#0  0x00007ffff64e1792 in isl_hash_table_init () from /home/kgk2/pack/mambaforge/envs/ceesd/lib/python3.10/site-packages/islpy/../../../libisl.so.23                   
#1  0x00007ffff64cc6e9 in isl_ctx_alloc_with_options () from /home/kgk2/pack/mambaforge/envs/ceesd/lib/python3.10/site-packages/islpy/../../../libisl.so.23
#2  0x00007ffff6b41a43 in islpy_expose_part1(pybind11::module_&)::{lambda()#1}::operator()() const ()
   from /home/kgk2/pack/mambaforge/envs/ceesd/lib/python3.10/site-packages/islpy/_isl.cpython-310-x86_64-linux-gnu.so
#3  0x00007ffff6bffab2 in pybind11::detail::initimpl::factory<islpy_expose_part1(pybind11::module_&)::{lambda()#1}, pybind11::detail::void_type (*)(), isl::ctx* (), pybind11::detail::void_type ()>::execute<pybind11::class_<isl::ctx, std::shared_ptr<isl::ctx> >>(pybind11::class_<isl::ctx, std::shared_ptr<isl::ctx> >&) &&::{lambda(pybind11::detail::value_and_holder&)#1}::operator()(pybind11::detail::value_and_holder&) const ()
```

### Installed packages

```shell
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
barvinok                  0.41.6               h682d088_0    conda-forge
black                     22.6.0          py310hff52083_2    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.6.15            ha878542_0    conda-forge
click                     8.1.3           py310hff52083_0    conda-forge
gf2x                      1.3.0                ha476b99_2    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
isl                       0.25                 h27087fc_0    conda-forge
islpy                     2022.2.1        py310h8139c57_2    conda-forge
jedi                      0.18.1             pyhd8ed1ab_2    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsqlite                 3.39.2               h753d276_1    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.12               h166bdaf_2    conda-forge
mypy_extensions           0.4.3           py310hff52083_5    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
ntl                       11.4.3               hef3c4d3_1    conda-forge
openssl                   3.0.5                h166bdaf_1    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pathspec                  0.9.0              pyhd8ed1ab_0    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
platformdirs              2.5.2              pyhd8ed1ab_1    conda-forge
prompt-toolkit            3.0.30             pyha770c72_0    conda-forge
prompt_toolkit            3.0.30               hd8ed1ab_0    conda-forge
ptpython                  3.0.20          py310hff52083_1    conda-forge
pygments                  2.12.0             pyhd8ed1ab_0    conda-forge
python                    3.10.5          ha86cf86_0_cpython    conda-forge
python_abi                3.10                    2_cp310    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
setuptools                65.0.1          py310hff52083_0    conda-forge
sqlite                    3.39.2               h4ff8645_1    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tzdata                    2022c                h191b570_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
```

### Environment info

```shell
active environment : ceesd
    active env location : /home/kgk2/pack/mambaforge/envs/ceesd
            shell level : 1
       user config file : /home/kgk2/.condarc
 populated config files : /home/kgk2/pack/mambaforge/.condarc
                          /home/kgk2/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __cuda=11.4=0
                          __linux=5.18.0=0
                          __glibc=2.33=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/kgk2/pack/mambaforge  (writable)
      conda av data dir : /home/kgk2/pack/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/nodefaults/linux-64
                          https://conda.anaconda.org/nodefaults/noarch
          package cache : /home/kgk2/pack/mambaforge/pkgs
                          /home/kgk2/.conda/pkgs
       envs directories : /home/kgk2/pack/mambaforge/envs
                          /home/kgk2/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.26.0 CPython/3.9.7 Linux/5.18.0-3-amd64 debian/testing glibc/2.33
                UID:GID : 3048:3048
             netrc file : None
           offline mode : False
```

**Comment by isuruf** [comment]
This is on a sandybridge or some older microarchitecture right?

**Comment by kaushikcfd** [comment]
It's Ivy Bridge, so slightly newer.

**Comment by kaushikcfd** [comment]
Thanks a lot @isuruf. https://github.com/conda-forge/barvinok-feedstock/pull/10 indeed fixes the issue.
